# This is a basic workflow to help analyze open API specs against API Guidelines

name: CI - Upload a spec

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, released ]
    tags: [v1.*]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Print tags
      - name: Print the input tag to STDOUT
        run: |
          echo The tags are ${{ github.event.inputs.tags }} 

      # Runs uploading a spec to API registry
      - name: Run a s
        run: |
          echo Upload a spec to api registry
          ./.bin/apiregistryctl service uploadspec openapi/spec2.json --service-id 2cc7a42b-a4c6-11ec-9bda-06d35fb06cae --version 1.0.0 --revision 1 --docType oas2
